Repository yorkie-team/yorkie, pull requests merged in 2021-01, with the labels that each got.

#133 Remove mongo-driver dependencies outside of mongo package
  yorkie/backend/backend.go
  yorkie/backend/db/change_info.go
  yorkie/backend/db/client_info.go
  yorkie/backend/db/db.go
  yorkie/backend/db/doc_info.go
  yorkie/backend/db/mongo/client.go
  yorkie/backend/db/mongo/decoder.go
  yorkie/backend/db/mongo/encoder.go
  yorkie/backend/db/snapshot_info.go
  yorkie/backend/db/synced_seq_info.go
  yorkie/backend/pubsub/pubsub.go
  yorkie/backend/sync/mutex_map.go
  yorkie/clients/client_service.go
  yorkie/packs/pack_service.go
  yorkie/rpc/server.go
  yorkie/types/snapshot_info.go
  yorkie/types/synced_seq_info.go
Labels: cleanup 🧹

#134 Add docker-publish action
  .github/workflows/ci.yml
  .github/workflows/docker-publish.yml
Labels: cleanup 🧹

#139 Add peer awareness design document
  design/peer-awareness.md
  design/template.md
Labels: documentation 📔

#143 Add garbage collection for text type design document
  design/gc-for-text-type.md
  design/media/block-wise-rga-structure.jpg
  design/template.md
Labels: wip 🏗

#144 Fix actorId conversion
  pkg/document/time/actor_id.go
  pkg/document/time/actor_id_test.go
  yorkie/backend/db/change_info.go
  yorkie/backend/db/change_info_test.go
Labels: bug 🐞
