Repository yorkie-team/yorkie, pull requests merged in 2023-05, with the labels that each got.

#531 Resolve Helm Chart Installation Fail on Custom Release Name
  build/charts/yorkie-argocd/values.yaml
  build/charts/yorkie-monitoring/README.md
  build/charts/yorkie-monitoring/templates/yorkie-servicemonitor.yaml
  build/charts/yorkie-monitoring/values.yaml
Labels: bug 🐞

#532 Integrate SDK RPC Server and Admin RPC Server to Single RPC Server
  admin/client.go
  build/charts/yorkie-cluster/templates/deployment.yaml
  build/charts/yorkie-cluster/templates/destination-rule.yaml
  build/charts/yorkie-cluster/templates/gateway.yaml
  build/charts/yorkie-cluster/templates/ingress.yaml
  build/charts/yorkie-cluster/templates/namespace.yaml
  build/charts/yorkie-cluster/templates/service.yaml
  build/charts/yorkie-cluster/templates/virtual-service.yaml
  build/charts/yorkie-cluster/values.yaml
  cmd/yorkie/commands.go
  cmd/yorkie/config/config.go
  cmd/yorkie/document/list.go
  cmd/yorkie/history.go
  cmd/yorkie/login.go
  cmd/yorkie/project/create.go
  cmd/yorkie/project/list.go
  cmd/yorkie/project/update.go
  cmd/yorkie/server.go
  server/admin/interceptors/default.go
  server/config.go
  server/config.sample.yml
  server/rpc/admin_server.go
  server/rpc/auth/token_manager.go
  server/rpc/interceptors/auth.go
  server/rpc/interceptors/context.go
  server/rpc/server.go
  server/rpc/server_test.go
  server/server.go
  test/bench/grpc_bench_test.go
  test/helper/helper.go
  test/integration/auth_webhook_test.go
  test/integration/document_test.go
  test/integration/history_test.go
  test/integration/retention_test.go
  test/integration/user_test.go
Labels: protocol changed 📝

#537 Revise Helm Charts for Production Installations
  build/charts/yorkie-argocd/templates/ingress.yaml
  build/charts/yorkie-argocd/templates/install.yaml
  build/charts/yorkie-cluster/templates/ingress.yaml
  build/charts/yorkie-cluster/values.yaml
  build/charts/yorkie-monitoring/templates/ingress.yaml
Labels: bug 🐞

#524 Remove panic method in crdt array
  pkg/document/crdt/array.go
  pkg/document/crdt/rga_tree_list.go
  pkg/document/crdt/rga_tree_split.go
  pkg/document/crdt/root_test.go
  pkg/document/crdt/text.go
  pkg/document/crdt/text_test.go
  pkg/document/json/array.go
  pkg/document/json/text.go
  pkg/splay/splay.go
  pkg/splay/splay_test.go
Labels: cleanup 🧹
