Repository yorkie-team/yorkie, pull requests merged in 2023-02, with the labels that each got.

#461 Update design documentation for v0.3.0
  design/data-structure.md
  design/media/data-structure.png
  design/media/document-editing-downstream.png
  design/media/document-editing-upstream.png
Labels: documentation 📔

#462 feat: remove priority queue from RHTPQMap and entire project
  api/converter/from_bytes.go
  api/converter/from_pb.go
  api/converter/to_bytes.go
  design/data-structure.md
  design/media/data-structure.png
  pkg/document/crdt/element_rht.go
  pkg/document/crdt/object.go
  pkg/document/crdt/object_test.go
  pkg/document/crdt/rht_pq_map.go
  pkg/document/document_test.go
  pkg/document/internal_document.go
  pkg/document/json/object.go
  pkg/document/operations/remove.go
  pkg/pq/priority_queue.go
  pkg/pq/priority_queue_test.go
  test/helper/helper.go
  test/integration/document_test.go
Labels: documentation 📔

#470 Fix invalid index of SplayTree with single node
  pkg/splay/splay.go
  pkg/splay/splay_test.go
Labels: bug 🐞, sdk ⚒️

#471 Change ClientDeactivateThreshold Type to String
  api/converter/from_pb.go
  api/converter/to_pb.go
  api/types/fields_validation.go
  api/types/project.go
  api/types/updatable_project_fields.go
  api/types/updatable_project_fields_test.go
  api/yorkie/v1/resources.pb.go
  api/yorkie/v1/resources.proto
  cmd/yorkie/project/update.go
  cmd/yorkie/server.go
  server/backend/backend.go
  server/backend/config.go
  server/backend/config_test.go
  server/backend/database/database.go
  server/backend/database/memory/database.go
  server/backend/database/memory/database_test.go
  server/backend/database/memory/housekeeping_test.go
  server/backend/database/mongo/client.go
  server/backend/database/mongo/client_test.go
  server/backend/database/mongo/indexes.go
  server/backend/database/project_info.go
  server/backend/database/project_info_test.go
  server/config.go
  server/config_test.go
  server/grpchelper/status.go
  server/projects/projects.go
  server/rpc/server_test.go
  test/bench/grpc_bench_test.go
  test/helper/helper.go
Labels: protocol changed 📝
