Repository yorkie-team/yorkie, pull requests merged in 2023-08, with the labels that each got.

#597 Fetch latest snapshot metadata to determine snapshot creation need
  server/backend/database/database.go
  server/backend/database/memory/database.go
  server/backend/database/mongo/client.go
  server/backend/database/snapshot_info.go
  server/backend/database/testcases/testcases.go
  server/packs/history.go
  server/packs/packs.go
  server/packs/snapshots.go
Labels: cleanup 🧹

#587 Add Pagination to Listing Projects for Housekeeping
  cmd/yorkie/server.go
  server/backend/database/database.go
  server/backend/database/memory/database.go
  server/backend/database/memory/housekeeping_test.go
  server/backend/database/mongo/client.go
  server/backend/database/mongo/client_test.go
  server/backend/database/testcases/testcases.go
  server/backend/housekeeping/config.go
  server/backend/housekeeping/config_test.go
  server/backend/housekeeping/housekeeping.go
  server/config.go
  server/config.sample.yml
  server/rpc/server_test.go
  test/helper/helper.go
Labels: enhancement 🌟

#613 Change 'Documents' from plural to singular in DocEvent
  api/converter/from_pb.go
  api/converter/to_pb.go
  api/types/event.go
  api/yorkie/v1/resources.pb.go
  api/yorkie/v1/resources.proto
  client/client.go
  pkg/document/internal_document.go
  server/backend/sync/memory/pubsub_test.go
  server/packs/packs.go
  server/rpc/admin_server.go
  server/rpc/yorkie_server.go
Labels: protocol changed 📝

#615 Fix treePos calculating logic for text node
  api/converter/from_pb.go
  pkg/document/crdt/tree.go
  pkg/document/crdt/tree_test.go
  pkg/index/tree.go
  test/integration/tree_test.go
Labels: bug 🐞

#622 Change TreeNode to have IDs instead of insPrev, insNext
  api/converter/from_pb.go
  api/converter/to_bytes.go
  api/yorkie/v1/resources.pb.go
  api/yorkie/v1/resources.proto
  pkg/document/crdt/tree.go
  pkg/index/tree.go
  test/integration/tree_test.go
Labels: protocol changed 📝

#608 Write concurrent tree editing document
  design/data-structure.md
  design/tree.md
Labels: documentation 📔

#630 Update Design Document for Missing Document Links and Ordering
  design/README.md
Labels: documentation 📔
