Repository yorkie-team/yorkie, pull requests merged in 2023-04, with the labels that each got.

#507 Add Yorkie Helm Charts
  .github/workflows/ci.yml
  .github/workflows/release-chart.yml
  .gitignore
  MAINTAINING.md
  Makefile
  build/build-binaries.sh
  build/charts/README.md
  build/charts/yorkie-argocd/.helmignore
  build/charts/yorkie-argocd/Chart.yaml
  build/charts/yorkie-argocd/README.md
  build/charts/yorkie-argocd/crds/install-crds.yaml
  build/charts/yorkie-argocd/templates/NOTES.txt
  build/charts/yorkie-argocd/templates/applications.yaml
  build/charts/yorkie-argocd/templates/ingress.yaml
  build/charts/yorkie-argocd/templates/install.yaml
  build/charts/yorkie-argocd/templates/repositories.yaml
  build/charts/yorkie-argocd/values.yaml
  build/charts/yorkie-cluster/.helmignore
  build/charts/yorkie-cluster/Chart.lock
  build/charts/yorkie-cluster/Chart.yaml
  build/charts/yorkie-cluster/README.md
  build/charts/yorkie-cluster/charts/mongodb/.helmignore
  build/charts/yorkie-cluster/charts/mongodb/Chart.yaml
  build/charts/yorkie-cluster/charts/mongodb/templates/service.yaml
  build/charts/yorkie-cluster/charts/mongodb/templates/statefulset.yaml
  build/charts/yorkie-cluster/templates/NOTES.txt
  build/charts/yorkie-cluster/templates/deployment.yaml
  build/charts/yorkie-cluster/templates/destination-rule.yaml
  build/charts/yorkie-cluster/templates/gateway.yaml
  build/charts/yorkie-cluster/templates/ingress-envoy-filter.yaml
  build/charts/yorkie-cluster/templates/ingress.yaml
  build/charts/yorkie-cluster/templates/namespace.yaml
  build/charts/yorkie-cluster/templates/service.yaml
  build/charts/yorkie-cluster/templates/virtual-service.yaml
  build/charts/yorkie-cluster/values.yaml
  build/charts/yorkie-monitoring/.helmignore
  build/charts/yorkie-monitoring/Chart.lock
  build/charts/yorkie-monitoring/Chart.yaml
  build/charts/yorkie-monitoring/README.md
  build/charts/yorkie-monitoring/templates/NOTES.txt
  build/charts/yorkie-monitoring/templates/ingress.yaml
  build/charts/yorkie-monitoring/templates/yorkie-servicemonitor.yaml
  build/charts/yorkie-monitoring/values.yaml
  build/docker/README.md
  build/docker/docker-compose-full.yml
  build/docker/docker-compose.yml
  build/docker/prometheus.yml
Labels: enhancement 🌟

#512 Add gRPC MaxConnectionAge & MaxConnectionAgeGrace options
  cmd/yorkie/server.go
  server/config.go
  server/config.sample.yml
  server/rpc/config.go
  server/rpc/server.go
  server/rpc/server_test.go
  test/helper/helper.go
Labels: enhancement 🌟

#522 Remove panic method in crdt text
  api/converter/from_bytes.go
  pkg/document/crdt/array.go
  pkg/document/crdt/counter.go
  pkg/document/crdt/element.go
  pkg/document/crdt/object.go
  pkg/document/crdt/primitive.go
  pkg/document/crdt/primitive_test.go
  pkg/document/crdt/rga_tree_split.go
  pkg/document/crdt/root.go
  pkg/document/crdt/root_test.go
  pkg/document/crdt/text.go
  pkg/document/crdt/text_test.go
  pkg/document/document.go
  pkg/document/json/array.go
  pkg/document/json/object.go
  pkg/document/json/text.go
  pkg/document/operations/add.go
  pkg/document/operations/edit.go
  pkg/document/operations/set.go
  pkg/document/operations/style.go
Labels: cleanup 🧹

#523 Add Sharded Cluster Mode Design Document
  design/README.md
  design/media/k8s-istio-implementation-internal-architecture.jpg
  design/media/long-lived-connection-split-brain.png
  design/media/ring-hash-example.jpg
  design/media/server-side-discovery.png
  design/media/sharded-cluster-mode-architecture.jpg
  design/sharded-cluster-mode.md
Labels: documentation 📔
